### PR TITLE
BaseAdapter: Validate direction of order by rules

### LINKED ISSUE #62: SQL Injection Bug in Icinga Web
## Describe the bug
The 'sort' parameter in various object viewport windows is vulnerable to SQL Injection.

## To Reproduce
Craft a derived table query and add to the url of various sort pages within the location bar
NB you may need to encode () with the %28 and %29 to reproduce depending on your environment

1. **POC URL:** https://<ip>/icingaweb2/icingadb/services?sort=services.state.severity %26%26 (SELECT * FROM (SELECT SLEEP(5)) alias)
2. ** ENCODED POC URL:** https://<ip>/icingaweb2/icingadb/services?sort=service.state.severity%20%26%26%20%28SELECT%20%2A%20FROM%20%28SELECT%20SLEEP%285%29%29%20alias%29

## Expected behavior
URLs should be parameterised and queries should be subject to validation

## Screenshots
As you can see in the below, I submitted a query to sleep for 15 seconds. This was executed as shown in the below
image

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.2
* Icinga Web 2 version (System - About): 2.11.2
* Web browser: Chrome, Firefox
* Icinga 2 version (icinga2 --version): 2.13.6
* Icinga DB version (icingadb --version): 1.0.0
* PHP version used (php --version): 7.4.3
* Server operating system and version: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by nilmerg**
fixes #62

### CODE REVIEW

File: src/Adapter/BaseAdapter.php [hunk 1]
```diff
@@ -96,4 +103,25 @@ protected function getTimezoneOffset()
...
     }
+
+    /**
+     * Validate the given select's order by rules
+     *
+     * @param Select $select
+     *
+     * @return void
+     */
+    protected function validateOrderBy(Select $select): void
```
Comment (lippserd) [inline src/Adapter/BaseAdapter.php:114]: I would have the method return bool so that there is one place that throws an exception and not multiple, since we have adapters that need to validate differently. You can also use the `OrderByInterface` as type here. If you don't want to return `bool` please add `@throws` and remove `@return`.

File: src/Adapter/BaseAdapter.php [hunk 2]
```diff
@@ -82,6 +84,11 @@ public function quoteIdentifier($identifiers)
 
     public function registerQueryBuilderCallbacks(QueryBuilder $queryBuilder)
     {
+        $queryBuilder->on(QueryBuilder::ON_ASSEMBLE_SELECT, function (Select $select): void {
```
Comment (lippserd) [inline src/Adapter/BaseAdapter.php:87]: The `Mssql` adapter should now call its parent method.

**Review by lippserd — CHANGES_REQUESTED** [review]

File: src/Adapter/BaseAdapter.php (hunk 1 above)
Comment (nilmerg) [reply src/Adapter/BaseAdapter.php:114]: Returning a bool doesn't allow for a specific exception message.

Comment (lippserd) [reply src/Adapter/BaseAdapter.php:114]: Yes, I thought so too, but I didn't find it too useful. But as I said, either is fine with me.

Comment (nilmerg) [reply src/Adapter/BaseAdapter.php:114]: Well, either that or a specific exception type.

Comment (lippserd) [reply src/Adapter/BaseAdapter.php:114]: The specific exception type is fine. Don't forget to use the `OrderByInterface` 😉.

File: src/Adapter/BaseAdapter.php [hunk 3]
```diff
@@ -96,4 +103,25 @@ protected function getTimezoneOffset()
...
     }
+
+    /**
+     * Validate the given select's order by rules
+     *
+     * @param Select $select
+     *
+     * @throws UnexpectedValueException In case the direction is invalid
+     */
+    protected function validateOrderBy(Select $select): void
```
Comment (lippserd) [inline src/Adapter/BaseAdapter.php:114]: `ORDER BY` is not exclusive to `SELECT` statements, please use the appropriate interface.

**Review by lippserd — CHANGES_REQUESTED** [review]

**Review by lippserd — APPROVED** [review]
